### PR TITLE
feat: add validator for eth addresses

### PR DESCRIPTION
**Pull request by msamsami**
* A new validator is added for the Ethereum address
* Crypto address validators combined into a new directory: `src/validators/crypto_addresses`

### CODE REVIEW

**Comment by msamsami** [comment]
Hi.
Please give me feedback on whether this is something you would like to be added to the library. If so, I can make the additional changes for versioning, changelog, etc.

Please note that I plan to extend this by adding more validators for TRX, ADA, and other crypto addresses.

Thanks!

**Comment by yozachar** [comment]
Hi, I'll review, but is it possible to make the external dependency, optional?

**Comment by msamsami** [comment]
> Hi, I'll review, but is it possible to make the external dependency, optional?

Sure. Something like a new group of optional dependencies named `crypto`, `crypto-address`,  or `crypto-addresses` that includes all the dependencies related to validators of crypto addresses. What do you think?
Please let me know your suggestions for the naming.

Finally, it can be used like `pip install validators[crypto-addresses]`.

**Comment by yozachar** [comment]
That sound exactly like what I was thinking.

**Comment by msamsami** [comment]
> That sound exactly like what I was thinking. `pip install validators[crypto-eth-addresses]`

It's done. Now, how do you think we should update the _pycqa.yaml_ workflow? I can explicitly include `pip install .[crypto-eth-addresses]` in "tooling" and "testing" jobs or create a new requirements.*.txt for it under package/ directory. Or is there a better way to do it? I'm trying to become close to your mindset here so that I can make more contributions with less confusion in the future. Thanks

**Comment by yozachar** [comment]
Change this:

https://github.com/python-validators/validators/blob/a7bcfda8902e0bcc42512c6630b0504ab9df65f0/package/roll.sh#L9-L10

to:

```sh
    # tooling
    pdm export --group tooling,crypto-eth-addresses -f requirements -o package/requirements.tooling.txt
```

Do the same in `roll.ps1`, and that should do it. Run either of one the scripts (bash or powershell, depending upon your OS), commit and push those changes to this PR.

Let's see if it works.

**Comment by msamsami** [comment]
> Change this:
> 
> https://github.com/python-validators/validators/blob/a7bcfda8902e0bcc42512c6630b0504ab9df65f0/package/roll.sh#L9-L10
> 
> to:
> 
> ```shell
>     # tooling
>     pdm export --group tooling,crypto-eth-addresses -f requirements -o package/requirements.tooling.txt
> ```
> 
> Do the same in `roll.ps1`. Run either of one the scripts (bash or powershell, depending upon your OS), commit and push those changes to this PR.
> 
> Let's see if it works.

It doesn't seem to be working. Isn't it because the optional dependencies are not installed here in the "testing" workflow?

https://github.com/python-validators/validators/blob/a7bcfda8902e0bcc42512c6630b0504ab9df65f0/.github/workflows/pycqa.yaml#L52-L53

**Comment by yozachar** [comment]
Ah, you are right, then let's add a redundant dependency group with:

```console
$ pdm add -dG testing pytest
```

This should change `pyproject.toml` to include:

```diff
[tool.pdm.dev-dependencies]
+ testing = ["pytest>=8.2.2"]
```

Do not remove `pytest` from `tooling`, it still is required there. Then in `roll.(sh|ps1)` generate a new file like so:

```diff
# tooling
pdm export --group tooling -f requirements -o package/requirements.tooling.txt
+# testing
+pdm export --group testing,crypto-eth-addresses -f requirements -o package/requirements.testing.txt
```

Finally in `pycqa.yaml`, you can make the following change:

```diff
-run: pip install pytest
+run: pip install -r package/requirements.testing.txt
```

Run the scripts, commit, push and try again.

**Comment by msamsami** [comment]
@yozachar All tests are passed except for the tooling workflow. Seems like we need `crypto-eth-addresses` in tooling dependencies as well. What do you think?

```diff
# tooling
-pdm export --group tooling -f requirements -o package/requirements.tooling.txt
+pdm export --group tooling,crypto-eth-addresses -f requirements -o package/requirements.tooling.txt
# testing
pdm export --group testing,crypto-eth-addresses -f requirements -o package/requirements.testing.txt
```

**Comment by yozachar** [comment]
Ah yes, I missed.

**Comment by msamsami** [comment]
It's all good now. 
Would you like to make a new release out of this PR? or after adding validators for more crypto addresses? If this counts as a release, I can update the `SECURITY.md` and `src/validators/__init__.py` files.

**Review by yozachar — APPROVED** [review]
This PR looks like a good candidate for `0.29.0`

**Comment by msamsami** [comment]
> This PR looks like a good candidate for `0.29.0`. Please go ahead.

I updated the version and changelog. Let me know if this wraps it up or if more needs to be done.

**Comment by yozachar** [comment]
I'll push a few changes, just some arrangements.

**Comment by yozachar** [comment]
What do you think?

**Comment by yozachar** [comment]
Thanks a lot for the PR!

**Pull request merged**
