### PR TITLE
feat: bumped version to 0.21.0

### PR DESCRIPTION
**Pull request by joe733**
- updates docs dependencies
- build workflow can be triggered manually
- updates changelog file `CHANGES.md` and `SECURITY.md`
- `no-commit-to-branch` hook prevents direct commit to `master`
- bumped `validators` package version to `0.21.0`

> This PR will be closed in an hour.

### CODE REVIEW

**Comment by joe733** [comment]
Hi @kvesteri, can you please add your PyPI API key to the repository secrets with it's name as `PYPI_API_TOKEN`.

https://github.com/python-validators/validators/blob/1f72b28808b42cf92a10f7a433e86ee15d64be0d/.github/workflows/build.yml#L38-L42

> Please ignore if you've already done so.

**Comment by joe733** [comment]
> Hi @kvesteri, can you please add your PyPI API key to the repository secrets with it's name as `PYPI_API_TOKEN`?

Or if you want to publish manually, please let me know, I can alter the workflow.

**Comment by kvesteri** [comment]
Hi @joe733 I added you as the owner of the project in PyPi. Now you can do this.

**Comment by joe733** [comment]
Okay, I've accepted the invite. Will do. Thanks.

**Pull request merged**
