### PR TITLE
TLD list testing added

### PR DESCRIPTION
**Pull request by aviiciii**
The TLD in the domain validator are checked against a valid list of TLDs from "https://data.iana.org/TLD/tlds-alpha-by-domain.txt"

This pull request solves #198

### CODE REVIEW

**Comment by aviiciii** [comment]
The tests on urls.py seems to fail. I'm not sure if changes on domain.py affect the latter. 

Also, the domain validator depends on the internet to fetch the list of TLDs, Do we need to have a static list in case the data can't be pulled?

**Comment by joe733** [comment]
> The tests on urls.py seems to fail. I'm not sure if changes on domain.py affect the latter.

Yes, URLs are composed of either ip-address or domain.

> Also, the domain validator depends on the internet to fetch the list of TLDs, Do we need to have a static list in case the data can't be pulled?

I'd prefer caching TLDs.

---

For now, I'll put this PR on hold, because:

1. It introduces an external dependency (which in this case, it can be resolved fairly easily)
2. Needs a bit of complex approach (like caching)
3. The PR seeks to address issues mentioned in https://github.com/python-validators/validators/issues/67 & https://github.com/python-validators/validators/issues/28#issuecomment-1423692636 which is more like answering the question `"Does this flower exists today?"` than answering `"Is that a flower?"`. The former is a bit more nuanced.
4. I'm working on a couple of core changes that would effect every upcoming PR.

---

Feel free to work on `1` & `2` if you like.

**Comment by aviiciii** [comment]
Ok cool, let me look what I can do on `1` and `2`

**Comment by joe733** [comment]
> Ok cool, let me look what I can do on 1 and 2

1. You can use Python's standard library to send request.
2. Look into caching in Python.

**Comment by davidt99** [comment]
Just want to bring the attention to this library that already handle this, maybe we can use it or take inspiration:
https://github.com/john-kurkowski/tldextract

**Pull request closed without merging**
