### PR TITLE
Expand validators.url to allow FQDNs that have IDNA A-labels

### PR DESCRIPTION
**Pull request by nullripper**
PR to resolve issue #78. In short, my changes make it so that URLs containing IDNA A-labels (e.g. "http://xn--j1ail.xn--p1ai") will pass validation instead of failing. Please refer to the issue for a more comprehensive explanation of the problem and my proposed solution.

### CODE REVIEW

**Comment by kvesteri** [comment]
Could you also add unit tests for this?

**Comment by nullripper** [comment]
Added unit tests as you requested, let me know if you need any more. Also made a slight change to the IDNA regex to allow for user:pass authentication; all the unit tests passed afterwards so that change should be good to go.

**Comment by kvesteri** [comment]
Tests are failing in CI

**Comment by jksecurity** [comment]
Hi guys,

I would love to use this bugfix. Would it be possible to see what's going wrong with the PR to get this merged?

Thanks!

**Pull request closed without merging**
